# Generated by Django 3.0.6 on 2020-05-21 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apidata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('calories', models.IntegerField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Snack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('calories', models.IntegerField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SnackInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apidata.Day')),
                ('snack', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apidata.Snack')),
            ],
        ),
        migrations.CreateModel(
            name='DrinkInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apidata.Day')),
                ('drink', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apidata.Drink')),
            ],
        ),
        migrations.AddField(
            model_name='day',
            name='drinks',
            field=models.ManyToManyField(through='apidata.DrinkInstance', to='apidata.Drink'),
        ),
        migrations.AddField(
            model_name='day',
            name='snacks',
            field=models.ManyToManyField(through='apidata.SnackInstance', to='apidata.Snack'),
        ),
    ]
