# Generated by Django 3.0.6 on 2020-05-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidata', '0002_auto_20200521_2154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='day',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='day',
            name='date',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='day',
            name='drinks',
            field=models.ManyToManyField(related_name='days', through='apidata.DrinkInstance', to='apidata.Drink'),
        ),
        migrations.AlterField(
            model_name='day',
            name='meals',
            field=models.ManyToManyField(related_name='days', through='apidata.MainMealInstance', to='apidata.MainMeal'),
        ),
        migrations.AlterField(
            model_name='day',
            name='snacks',
            field=models.ManyToManyField(related_name='days', through='apidata.SnackInstance', to='apidata.Snack'),
        ),
    ]
