# Generated by Django 3.0.6 on 2020-05-26 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apidata', '0004_auto_20200526_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainmealinstance',
            name='day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apidata.Day'),
        ),
        migrations.AlterField(
            model_name='mainmealinstance',
            name='mainMeal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apidata.MainMeal'),
        ),
    ]
