# Generated by Django 3.0.6 on 2020-05-26 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apidata', '0005_auto_20200526_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainmealinstance',
            name='day',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='apidata.Day'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mainmealinstance',
            name='mainMeal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apidata.MainMeal'),
            preserve_default=False,
        ),
    ]
