# Generated by Django 3.0.6 on 2020-05-26 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apidata', '0006_auto_20200526_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinkinstance',
            name='day',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apidata.Day'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='drinkinstance',
            name='drink',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apidata.Drink'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='snackinstance',
            name='day',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apidata.Day'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='snackinstance',
            name='snack',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apidata.Snack'),
            preserve_default=False,
        ),
    ]
