# Generated by Django 3.0.6 on 2020-05-27 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apidata', '0007_auto_20200526_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainmealinstance',
            name='mainMeal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_meal_instances', to='apidata.MainMeal'),
        ),
    ]
