# Generated by Django 3.0.6 on 2020-05-27 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apidata', '0008_auto_20200527_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainmealinstance',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_meal_instances', to='apidata.Day'),
        ),
        migrations.AlterField(
            model_name='mainmealinstance',
            name='mainMeal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apidata.MainMeal'),
        ),
    ]
