# Generated by Django 3.0.6 on 2020-05-27 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apidata', '0009_auto_20200527_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='calorie_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drinkinstance',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drink_instances', to='apidata.Day'),
        ),
        migrations.AlterField(
            model_name='snackinstance',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snack_instances', to='apidata.Day'),
        ),
    ]
