# Generated by Django 3.0.6 on 2020-05-27 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apidata', '0010_auto_20200527_2044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='day',
            old_name='calorie_count',
            new_name='calories',
        ),
    ]
