# Generated by Django 3.0.6 on 2020-05-29 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidata', '0011_auto_20200527_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='mainmeal',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='snack',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
